// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzKKtLsZmF9ZkQZYtfOZ1frIvPWVlkAOk',
    appId: '1:1082222861713:web:50bf669e9cec731808ce30',
    messagingSenderId: '1082222861713',
    projectId: 'taskora-d1af6',
    authDomain: 'taskora-d1af6.firebaseapp.com',
    storageBucket: 'taskora-d1af6.firebasestorage.app',
    measurementId: 'G-C6NMR4EFXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWltkae20wngZVC0bQl1DuyOST4GjGtgg',
    appId: '1:1082222861713:android:5c8502d2a58c6b2d08ce30',
    messagingSenderId: '1082222861713',
    projectId: 'taskora-d1af6',
    storageBucket: 'taskora-d1af6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEPRbMJRaNbtAkY8xT1FodyDULNxCPJoA',
    appId: '1:1082222861713:ios:6acfc8af60c36e6e08ce30',
    messagingSenderId: '1082222861713',
    projectId: 'taskora-d1af6',
    storageBucket: 'taskora-d1af6.firebasestorage.app',
    iosBundleId: 'com.coddiv.taskora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEPRbMJRaNbtAkY8xT1FodyDULNxCPJoA',
    appId: '1:1082222861713:ios:6acfc8af60c36e6e08ce30',
    messagingSenderId: '1082222861713',
    projectId: 'taskora-d1af6',
    storageBucket: 'taskora-d1af6.firebasestorage.app',
    iosBundleId: 'com.coddiv.taskora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzKKtLsZmF9ZkQZYtfOZ1frIvPWVlkAOk',
    appId: '1:1082222861713:web:d670604643eb999708ce30',
    messagingSenderId: '1082222861713',
    projectId: 'taskora-d1af6',
    authDomain: 'taskora-d1af6.firebaseapp.com',
    storageBucket: 'taskora-d1af6.firebasestorage.app',
    measurementId: 'G-ZKVF1V52R5',
  );
}
